name: serface
description: A simple tablet UI for my sister.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nextcloud:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/nextcloud
      ref: f6f3597c6396a9a2e29f1dc431815a0ff2e16c64
  ionicons: ^0.2.2
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15
  path: ^1.8.3
  file: ^6.1.4
  nm: ^0.5.0
  upower: ^0.7.0
  media_kit: ^1.1.8+2
  youtube_explode_dart: ^2.0.2

dependency_overrides:
  dynamite_runtime:
    git:
      url: https://github.com/provokateurin/nextcloud-neon
      path: packages/dynamite/dynamite_runtime
      ref: f6f3597c6396a9a2e29f1dc431815a0ff2e16c64

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
